name: breez-lnurl DEV CI/CD

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: breez-lnurl-dev-${{ github.event_name == 'push' && 'develop' || github.run_id }}
  cancel-in-progress: true

env:
  DOCKER_TAGS: lightningdotspacecom/breez-lnurl:beta

jobs:
  build-and-push:
    name: Build and push to DEV
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: crates/breez-sdk/lnurl/Dockerfile
          push: true
          tags: ${{ env.DOCKER_TAGS }}
          platforms: linux/arm64
